global:
  email-reply-to: bigdata-hbase-team@salesforce.com # Change this to your group's e-mail address!
  email-only-last-committer-on-dev-branch: true
  timeout: 300
  production-branches: 
    - 2.5.10-sfdc-13
stages:
  integration-test:
    - maven-verify:
        maven-publish-jar-args: -DskipITs -Dmaven.test.failure.ignore=true -Dsurefire.testFailureIgnore=true
