
sonar.modules=hbase-checkstyle,hbase-protocol-shaded,hbase-common,hbase-metrics-api,hbase-hadoop-compat,hbase-metrics,hbase-hadoop2-compat,hbase-client,hbase-zookeeper,hbase-replication,hbase-resource-bundle,hbase-http,hbase-asyncfs,hbase-procedure,hbase-server,hbase-mapreduce,hbase-testing-util,hbase-thrift,hbase-rsgroup,hbase-shell,hbase-endpoint,hbase-it,hbase-rest,hbase-examples,hbase-external-blockcache,hbase-hbtop
sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes
sonar.java.libraries=target/*.jar
sonar.exclusions=**/target/**,**/*.cpp,**/*.c,**/*.rb,**/*.py,**/*.php,**/*.proto,**/generated/**/*
sonar.cpp.file.suffixes=-
sonar.c.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPath=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


