
sonar.modules=hbase-checkstyle,hbase-annotations,hbase-build-configuration,hbase-logging,hbase-protocol-shaded,hbase-common,hbase-metrics-api,hbase-hadoop-compat,hbase-metrics,hbase-hadoop2-compat,hbase-client,hbase-zookeeper,hbase-replication,hbase-resource-bundle,hbase-http,hbase-asyncfs,hbase-procedure,hbase-server,hbase-mapreduce,hbase-testing-util,hbase-thrift,hbase-rsgroup,hbase-shell,hbase-endpoint,hbase-it,hbase-rest,hbase-examples,hbase-shaded,hbase-shaded-client,hbase-shaded-client-byo-hadoop,hbase-shaded-mapreduce,hbase-external-blockcache,hbase-hbtop,hbase-compression,hbase-compression-aircompressor,hbase-compression-brotli,hbase-compression-lz4,hbase-compression-snappy,hbase-compression-zstd,hbase-assembly,hbase-shaded-testing-util,hbase-shaded-testing-util-tester,hbase-shaded-check-invariants,hbase-shaded-with-hadoop-check-invariants,hbase-archetypes,hbase-client-project,hbase-shaded-client-project,hbase-archetype-builder
sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes
sonar.java.libraries=target/*.jar
sonar.exclusions=**/target/**,**/*.cpp,**/*.c,**/*.rb,**/*.py,**/*.php,**/*.proto,**/generated/**/*
sonar.cpp.file.suffixes=-
sonar.c.file.suffixes=-
sonar.objc.file.suffixes=-

sonar.junit.reportPaths=target/surefire-reports
sonar.jacoco.reportPath=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


